# Site settings
title: The Lifes and Times of Learning to Code
header-img: img/home-bg.png
email: robwash@gmail.com
copyright_name: RWashington2014
description: > # this means to ignore newlines until "baseurl:"
  Ruby, Javascript and more.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  RWashington2014
learn_profile: RWashington2014
email_username: robwash@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
